import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import ReactorViewport from './ReactorViewport.jsx';
import {verdict,number} from './metrics.js';
import './style.css';

function Chart({runs}) {
  const [cursor,setCursor]=useState(20);
  const end=Math.max(...runs.map(r=>r.measurement.observed_through_s));
  const colors=['#45c9bf','#efb968'];
  return <div className="chart"><svg viewBox="0 0 560 255" role="img" aria-label="Minimum tracer concentration across nine gas probes over time; the dashed line marks 90 percent">
    {[0,25,50,75,100].map(v=><g key={v}><line x1="42" x2="540" y1={215-v*1.9} y2={215-v*1.9} stroke="#30424e"/><text x="33" y={219-v*1.9} textAnchor="end">{v}</text></g>)}
    <line x1="42" x2="540" y1="44" y2="44" stroke="#dae3ea" strokeDasharray="5 5"/><text x="535" y="38" textAnchor="end">90% threshold</text>
    {runs.map((r,i)=><polyline key={r.id} fill="none" stroke={colors[i]} strokeWidth="2.7" points={r.curve.map(p=>`${42+p.time_s/end*498},${215-p.minimum_label*190}`).join(' ')}/>)}
    {[0,.25,.5,.75,1].map(v=><text key={v} x={42+v*498} y="235" textAnchor="middle">{number(end*v,0)} s</text>)}
    <text x="42" y="13">Tracer concentration (%)</text>
  </svg><div className="legend">{runs.map((r,i)=><span key={r.id}><i style={{background:colors[i]}}/>{r.name}</span>)}</div>
  <label className="scrubber">Inspect time: {Math.min(cursor,end).toFixed(1)} s<input aria-label="Inspect chart time" type="range" min="0" max={end} step="0.05" value={Math.min(cursor,end)} onChange={e=>setCursor(+e.target.value)}/></label>
  <div className="readouts">{runs.map(r=>{const p=r.curve.reduce((a,b)=>Math.abs(b.time_s-Math.min(cursor,end))<Math.abs(a.time_s-Math.min(cursor,end))?b:a);return <span key={r.id}>{r.id==='variant'?'Five inlets':r.id==='baseline'?'Four inlets':'Selected run'}: {(100*p.minimum_label).toFixed(2)}%</span>})}</div></div>;
}

function Assistant({data}) {
 const [tab,setTab]=useState('compare');
 const base=data.runs[0],variant=data.runs[1];
 return <><div className="eyebrow">Recorded workflow · no live model</div><h2>Evidence assistant</h2><p>An engineer asks a question. The local agent clarifies the study, prepares a plan, uses controlled tools and reports checked evidence.</p>
 <div className="tabs">{[['compare','Compare designs'],['review','Reject weak evidence'],['plan','Plan an experiment']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='compare'?<div className="answer"><h3>Would adding a central inlet deliver nitrogen sooner?</h3><ol><li><b>Clarify supply.</b> The executed study kept 75 sccm per inlet: 300 → 375 sccm overall.</li><li><b>Prepare and review.</b> Create a separate five-inlet mesh. Record conditional exploratory approval of the concave-cell warning.</li><li><b>Execute.</b> Calculate steady nitrogen flow and matched 40-second passive-tracer histories.</li><li><b>Check and report.</b> All nine probes reached 90% at {number(base.measurement.arrival_time_s)} s versus {number(variant.measurement.arrival_time_s)} s. Both tracer histories passed the recorded screens.</li></ol><p className="warning">The observed 7.79-second reduction combines layout and supply changes. It is not an isolated geometry effect or proof of an optimum.</p></div>:tab==='review'?<div className="answer"><h3>Can the early fine run support a recommendation?</h3><p><b>No — insufficient evidence.</b> The early fine tracer history ended at 10.2 seconds and exceeded the permitted concentration bounds. A small conservation error cannot override failed bounds or an incomplete history.</p><p>The corrected fine reference was assessed separately. Select both runs above to inspect their checks and histories.</p></div>:<div className="answer"><h3>What would a fair geometry-only comparison require?</h3><p>Keep total nitrogen at 300 sccm: four inlets at 75 each versus five at 60 each. Keep gas properties, probe positions, numerical settings and comparison metrics consistent.</p><p>Define an arrival deadline and permitted arrival spread; review mesh findings; run flow and tracer checks; then compare eligible results. This fixed-total-supply study is a proposed next experiment, not a result in this site.</p></div>}
 <p className="muted">These are curated summaries of the demonstrated local workflow. This public viewer does not send prompts, approve studies or launch simulations.</p></>;
}

function App(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[id,setId]=useState('variant'),[target,setTarget]=useState('35');
 useEffect(()=>{fetch('/data/study.json').then(r=>{if(!r.ok)throw Error('Evidence could not be loaded');return r.json()}).then(setData).catch(e=>setError(e.message))},[]);
 if(error)return <main><h1>Unable to load evidence</h1><p role="alert">{error}</p><button onClick={()=>location.reload()}>Retry</button></main>;
 if(!data)return <main><p role="status">Loading verified study evidence…</p></main>;
 const run=data.runs.find(r=>r.id===id),comparison=['baseline','variant'].includes(id),chartRuns=comparison?data.runs.slice(0,2):[run];
 return <main><header><div><div className="eyebrow">KTP application showcase · Jubal Jacob</div><h1>From a design question<br/>to simulation evidence.</h1><p>Explore nitrogen delivery in a simplified 3D reactor and the controlled AI workflow used to investigate it.</p></div><a className="repo" href="https://github.com/jubaljacob/CFD_demo_KTP">View source ↗</a></header>
 <div className="notice"><b>Interactive results viewer</b><span>Completed local simulations · saved evidence · no live AI or CFD execution</span></div>
 <div className="selector"><label>Explore a completed run<select value={id} onChange={e=>setId(e.target.value)}>{data.runs.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><span className={run.valid?'badge':'badge bad'}>{run.valid?'Tracer checks passed':'Evidence rejected'}</span><span>13332 Pa · 383.15 K · nitrogen</span></div>
 <div className="grid"><section className="card results"><div className="eyebrow">01 / Measured response</div><h2>{comparison?'Four versus five inlets':'Reference study'}</h2><p>Time for <b>all nine gas probes</b>, 2 mm above the wafer, to reach 90% of the incoming tracer concentration.</p>
 <div className="metrics">{chartRuns.map(r=><div key={r.id}><span>{r.id==='variant'?'Five inlets':r.id==='baseline'?'Four inlets':r.name}</span><strong>{r.valid?number(r.measurement.arrival_time_s):'Rejected'}{r.valid&&<small> s</small>}</strong><span>{r.supply_sccm} sccm nitrogen</span></div>)}</div>
 <Chart key={comparison?'comparison':id} runs={chartRuns}/>
 <div className="target"><label>Arrival target (seconds)<input type="number" min="0.1" max="120" step="0.1" value={target} onChange={e=>setTarget(e.target.value)}/></label><p aria-live="polite">{verdict(run,target===''?NaN:Number(target))}</p></div><p className="muted">Target changes only assess saved results. Linear interpolation between recorded samples; arrival must persist at later samples. This is not 90% wafer-area coverage.</p>
 {comparison&&<p className="warning"><b>Interpretation:</b> five inlets reached the threshold 7.79 s sooner, with 25% more gas supplied per minute. The five-inlet mesh and time-step sensitivity remain untested.</p>}</section>
 <section className="card viewport"><div className="eyebrow">02 / Reactor visualisation</div><h2>{run.geometry==='five'?'Five-inlet reactor':'Four-inlet reactor'}</h2><ReactorViewport key={run.flow} geometryUrl={'/data/geometry-'+run.geometry+'.json'} flowUrl={'/data/flow-'+run.flow+'.json'} label={run.name}/></section>
 <section className="card checks"><div className="eyebrow">03 / Evidence and limits</div><h2>Checks before conclusions</h2><p>Selected run: <b>{run.name}</b></p><ul className="checklist">{Object.entries(run.checks).map(([k,v])=><li key={k}><span>{k.replaceAll('_',' ')}</span><b className={v?'pass':'fail'}>{v?'Pass':'Fail'}</b></li>)}</ul><p>Largest tracer balance error / chamber volume: <b>{run.max_balance_error_over_volume.toExponential(2)}</b>.</p><div className="warning"><b>Exploratory use only.</b> The five-inlet mesh has 76 concave cells and 78 concave faces; one strict mesh check failed. Conditional review was recorded, not an unconditional mesh pass.</div><p>Isothermal, passive nitrogen transport in a simplified reactor inspired by published work. No plasma, chemical reactions, heating, adsorption or deposition. No claim of validated Oxford Instruments equipment performance or autonomous optimisation.</p>
 <details><summary>Study evidence and downloads</summary><p>Completed {new Date(data.finished_at).toLocaleDateString('en-GB')}. Study {data.study_id}. Compact evidence is supplied; the full solver fields and executable local agent are outside this public viewer.</p><div className="downloads"><a href="/data/study.json" download>Results JSON</a><a href="/data/source-checksums.json" download>Original source fingerprints</a>{['baseline','variant'].map(r=><React.Fragment key={r}><a href={'/evidence/'+r+'/probes.txt'} download>{r} nine-probe history</a><a href={'/evidence/'+r+'/budget.csv'} download>{r} tracer balance</a></React.Fragment>)}</div></details></section>
 <section className="card assistant"><Assistant data={data}/></section></div>
 <section className="references"><h2>Sources and learning</h2><p>This application project began as a first study of CFD, progressing from cavity flow and analytical channel-flow checks to a 3D nitrogen experiment.</p><ul><li><a href="https://doi.org/10.1063/1.4742991">Kimes, Moore & Maslar (2012), reactor paper</a> — geometry inspiration; the demonstration does not reproduce the full experimental physics.</li><li><a href="https://doi.org/10.6028/NIST.TN.2279">Burgess, NIST Technical Note 2279 (2024)</a> — gas diffusion reference.</li><li><a href="https://www.openfoam.com/documentation/tutorial-guide">OpenCFD OpenFOAM tutorials and documentation</a> — finite-volume modelling, meshing, flow and scalar transport; local solver version v2512.</li><li><a href="https://docs.paraview.org/en/latest/">ParaView documentation</a> — inspecting meshes, probe histories, exported streamlines and tracer playback.</li><li><a href="https://doi.org/10.1002/aidi.202500174">ChatCFD</a> and <a href="https://arxiv.org/abs/2605.06607">arXiv:2605.06607</a> — agent-assisted CFD design ideas; no claim to reproduce either research system.</li></ul></section><footer>Independent application showcase · Research-inspired demonstrator · AI-assisted development</footer></main>;
}
createRoot(document.getElementById('root')).render(<App/>);
